import clsx from 'clsx';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

import { Providers } from './providers';

export const sfProText = localFont({
  src: [
    { path: '../../public/fonts/SFPro/SF-Pro-Text-Regular.otf', weight: '400' },
    { path: '../../public/fonts/SFPro/SF-Pro-Text-Medium.otf', weight: '500' },
    {
      path: '../../public/fonts/SFPro/SF-Pro-Text-Semibold.otf',
      weight: '600',
    },
    { path: '../../public/fonts/SFPro/SF-Pro-Text-Bold.otf', weight: '700' },
  ],
  variable: '--font-sf-text',
});

export const metadata: Metadata = {
  title: 'Todo List App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={clsx(sfProText.variable, 'antialiased')}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
